### ISSUE TITLE
HVDM distance

### ISSUE THREAD

**Issue by vocarvalho** [paobranco/UBL#17]
I found your UBL package. This is helping me a lot. However, I am having problems with the HVDM distance with nominal features. I looked at the code on github, I did a lot of testing, but I can't understand what's going on. Attached I am sending some tests I did to understand. The distance values are not what I expected. Could you help me understand what's going on?

Code
col1 <-   factor(c("a", "a", "c", "c"))
col2 <-   factor(c("b", "d", "d", "g"))
col3 <-   factor(c("c", "b", "e", "h"))
col4 <-   factor(c("x", "x", "y", "y"))
df <- data.frame(col1,   col2, col3, col4)
dist2 <- distances(4, df,   "HVDM")
dist2

![code](https://user-images.githubusercontent.com/82233846/114224779-e5ad4e00-9947-11eb-9675-710a14305648.png)
![ubl](https://user-images.githubusercontent.com/82233846/114224801-ed6cf280-9947-11eb-9570-64fe82123a8e.png)
![comp](https://user-images.githubusercontent.com/82233846/114224821-f4940080-9947-11eb-97ca-95ad0050b1c7.png)

[Computation.xls](https://github.com/paobranco/UBL/files/6287815/Computation.xls)

**Comment by paobranco** [comment]
Hello,

first of all thank you for your interest on UBL package!

A new version (UBL 0.0.7) was released on CRAN in March 29, 2021.
This version already corrects this issue with HVDM metric.
Please download the new UBL version.

**Comment by vocarvalho** [comment]
Thanks a lot.
